apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-lidarr
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
