# Prometheus HelmRelease via kube-prometheus-stack
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: latest
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-client
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 8Gi
    grafana:
      enabled: true
      persistence:
        enabled: true
        storageClassName: nfs-client
        size: 2Gi
      initChownData: false
      ingress:
        enabled: true
        hosts:
          - grafana.local
