# Prometheus monitoring configuration
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  chart:
    repository: "https://prometheus-community.github.io/helm-charts"
    name: prometheus
    version: "15.0.0"