apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.5.5
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            port: 8123
    persistence:
      config:
        enabled: true
        existingClaim: nfs-pvc
    ingress:
      main:
        enabled: true
        hosts:
          - host: homeassistant.local
            paths:
              - path: /
    env:
      - name: SERVER_HOSTNAME
        value: "homeassistant.local"
