# Home Assistant on k3s, using helm-controller (Flux) with NFS volume
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: "13.4.2"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    persistence:
      enabled: true
      existingClaim: nfs-pvc
      size: 20Gi   # Optional, not used if using an existingClaim
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: homeassistant.local
          paths: ["/"]
