apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.7.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/linuxserver/lidarr
      tag: 1.9.0.4325-ls180
    persistence:
      config:
        enabled: true
        existingClaim: nfs-pvc
    ingress:
      main:
        enabled: true
        hosts:
          - host: lidarr.local
            paths:
              - path: /
