apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: lidarr
      version: ">=11.0.0"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    persistence:
      existingClaim: nfs-pvc
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: lidarr.local
          paths: ["/"]
