apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.7.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: jacobalberty/unifi
      tag: v8.1.127
    persistence:
      config:
        enabled: true
        existingClaim: nfs-pvc
    ingress:
      main:
        enabled: true
        hosts:
          - host: unifi.local
            paths:
              - path: /
