apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pihole
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: ">=2.0.0"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  values:
    serviceWeb:
      type: ClusterIP
    persistence:
      existingClaim: nfs-pvc
    ingress:
      enabled: true
      hosts:
        - host: "pihole.local"
          paths:
            - /
