apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: prowlarr
      version: ">=6.0.0"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    persistence:
      enabled: true
      existingClaim: nfs-pvc
      size: 2Gi   # Optional, not used if using an existingClaim
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: prowlarr.local
          paths: ["/"]
