apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/prowlarr
              tag: latest
    service:
      main:
        enabled: true
        ports:
          http:
            port: 9696
    persistence:
      config:
        enabled: true
        existingClaim: nfs-pvc-prowlarr
    ingress:
      main:
        enabled: true
        hosts:
          - host: prowlarr.local
            paths:
              - path: /
