apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: prowlarr
      version: "4.5.2"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    persistence:
      existingClaim: nfs-pvc
    ingress:
      enabled: true
      hosts:
        - host: "prowlarr.local"
          paths:
            - /
