apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: radarr
      version: "1.20.0"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    persistence:
      existingClaim: nfs-pvc
    ingress:
      enabled: true
      hosts:
        - host: "radarr.local"
          paths:
            - /
