# Ubiquiti Unifi Controller HelmRelease (replace image/tag as needed)
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: unifi
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi
      version: ">=0.1.0"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    persistence:
      enabled: true
      existingClaim: nfs-pvc
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: unifi.local
          paths: ["/"]
