apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: jacobalberty/unifi
              tag: latest
    service:
      main:
        enabled: true
        ports:
          # Expose HTTPS port for the controller UI
          https:
            enabled: true
            port: 8443
            protocol: TCP
            targetPort: 8443
    persistence:
      config:
        enabled: true
        existingClaim: nfs-pvc
    ingress:
      main:
        enabled: true
        # Host definition for Ingress
        hosts:
          - host: unifi.local
            paths:
              - path: /
        # Enable TLS for HTTPS passthrough (Traefik will terminate TLS or passthrough if configured)
        tls:
          - hosts:
              - unifi.local
