apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: jacobalberty/unifi
              tag: latest
    # Service must expose only HTTPS (8443) for the Unifi UI
    service:
      main:
        enabled: true
        ports:
          https:
            enabled: true
            port: 8443
            protocol: TCP
            targetPort: 8443
    persistence:
      config:
        enabled: true
        existingClaim: nfs-pvc
