apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: jacobalberty/unifi
              tag: v8.1.127
    service:
      main:
        enabled: true
        ports:
          http:
            port: 8443
    persistence:
      config:
        enabled: true
        existingClaim: nfs-pvc
    ingress:
      main:
        enabled: true
        hosts:
          - host: unifi.local
            paths:
              - path: /
        servicePort: http
