apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: jacobalberty/unifi
              tag: latest
        # Custom DNS config to ensure pod DNS works
        dnsPolicy: None
        dnsConfig:
          nameservers:
            - 8.8.8.8         # Google's DNS (fallback)
            - 1.1.1.1         # Cloudflare DNS (fallback)
          options:
            - name: ndots
              value: "1"
          searches:
            - localdomain
    # Expose all necessary ports for UI, adoption, and device discovery
    service:
      main:
        enabled: true
        type: LoadBalancer  # Ensures pods are accessible from your LAN
        ports:
          ui:
            enabled: true
            port: 8443        # Controller web UI (HTTPS)
            protocol: TCP
            targetPort: 8443
          inform:
            enabled: true
            port: 8080        # Device adoption/inform
            protocol: TCP
            targetPort: 8080
          stun:
            enabled: true
            port: 3478        # STUN discovery
            protocol: UDP
            targetPort: 3478
          discovery:
            enabled: true
            port: 10001       # Layer 2 device discovery
            protocol: UDP
            targetPort: 10001
          speedtest:
            enabled: true
            port: 6789        # Speed test (optional)
            protocol: TCP
            targetPort: 6789
    persistence:
      config:
        enabled: true
        existingClaim: nfs-pvc
