# Traefik Ingress controller HelmRelease (k3s default, but can be customized)
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: ">=27.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    additionalArguments:
      # Enable the insecure dashboard for easy access (disable in prod!)
      - "--api.insecure=true"
      # Explicitly enable the dashboard; required for visibility via /dashboard and /api
      - "--api.dashboard=true"
    ingressRoute:
      dashboard:
        enabled: true
    service:
      type: LoadBalancer
